# Fukushima

Explore datasets from this search: [fukushima cesium](https://datasetsearch.research.google.com/search?query=fukushima%20cesium&docid=L2cvMTFtX2pxdmpqOA%3D%3D)

Use the following two: [Result 1](https://datasetsearch.research.google.com/search?query=fukushima%20cesium&docid=L2cvMTFtX2pxdmpqOA%3D%3D) and [Result 2](https://www.bco-dmo.org/dataset/3625)


The first dataset is very wide.  Also, the spatial data is encoded different across the two (sigh).  

## Note

The BCO-DMO data can be pulled down in CSV or NetCDF, though this is a simple NetCDF for a tabular data.

In [15]:
import pandas as pd

In [16]:
#load BCODMO

dfurl1  = "https://erddap.bco-dmo.org/erddap/tabledap/bcodmo_dataset_3625.csv"

bcodmo = pd.read_csv(dfurl1)

In [17]:
bcodmo.head()

,sta,date,time2,date_local,time_local,latitude,longitude,event,depth_n,Cs137,err_Cs137,Cs134,err_Cs134,Cs134_Cs137,err_Cs134_Cs137
0,dimensionless,unitless,hhmm,yymmdd,hhmm,degrees_north,degrees_east,dimensionless,meters,Bq/meter^3,Bq/meter^3,Bq/meter^3,Bq/meter^3,Bq/meter^3,Bq/meter^3
1,2.0,20110606,2135,20110607,0635,34.498,147.0,11158_0632,2,2.59,0.61,1.70,0.5,1.53,0.57
2,4.0,20110607,2145,20110608,0645,35.502,146.999,11159_0645,2,316.94,9.76,314.86,8.64,1.01,0.04
3,5.0,20110608,0320,20110608,1220,35.993,147.016,11159_1220,2,25.23,0.74,23.33,0.66,1.08,0.04
4,7.0,20110608,1538,20110609,0038,36.991,147.0,11160_0038,2,201.84,5.26,203.07,4.25,0.99,0.03

In [18]:
bcodmo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sta              48 non-null     object
 1   date             48 non-null     object
 2   time2            48 non-null     object
 3   date_local       48 non-null     object
 4   time_local       48 non-null     object
 5   latitude         48 non-null     object
 6   longitude        48 non-null     object
 7   event            48 non-null     object
 8   depth_n          48 non-null     object
 9   Cs137            48 non-null     object
 10  err_Cs137        48 non-null     object
 11  Cs134            48 non-null     object
 12  err_Cs134        43 non-null     object
 13  Cs134_Cs137      48 non-null     object
 14  err_Cs134_Cs137  43 non-null     object
dtypes: object(15)
memory usage: 5.8+ KB

In [19]:
#load 
dfurl2 = "https://zenodo.org/record/4268843/files/CsDB-ver1.1.xlsx?download=1"
oa = pd.read_excel(dfurl2)

In [20]:
oa.head()

,Record_number,FFPRI_code,Source_type,Source_number,First_author,Year_published,Elevation,Prefecture,Municipality,Site_name,...,Version_of_modMEXT,Soil_profile_number,Flag_duplication,Related_references,MEXT_Cs137_2011.3.11.corrected,modMEXT_Cs137_by_Kato_et_al._2019_2011.3.11corrected,Sampling_date_estimated,Corrected_date_estimated,Activity_corrected_to_sampling_date,Inventory_corrected_to_sampling_date
0,1,p1-1,Paper,p1,Pumpanen,2016,370.0,Fukushima,Date,Date,...,2011-07-02,NaN,NaN,NaN,277.54584,306.01767,2012-09-15,NaT,1622,NaN
1,2,p1-2,Paper,p1,Pumpanen,2016,370.0,Fukushima,Date,Date,...,2011-07-02,NaN,NaN,NaN,277.54584,306.01767,2012-09-15,NaT,82,NaN
2,3,p1-3,Paper,p1,Pumpanen,2016,370.0,Fukushima,Date,Date,...,2011-07-02,NaN,NaN,NaN,277.54584,306.01767,2012-09-15,NaT,135,NaN
3,4,p1-4,Paper,p1,Pumpanen,2016,370.0,Fukushima,Date,Date,...,2011-07-02,1.0,NaN,NaN,277.54584,306.01767,2014-06-01,NaT,31842,NaN
4,5,p1-5,Paper,p1,Pumpanen,2016,370.0,Fukushima,Date,Date,...,2011-07-02,1.0,NaN,NaN,277.54584,306.01767,2014-06-01,NaT,2273,NaN

In [21]:
oa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16480 entries, 0 to 16479
Data columns (total 95 columns):
 #   Column                                                Non-Null Count  Dtype
---  ------                                                --------------  -----
 0   Record_number                                         16480 non-null  int64
 1   FFPRI_code                                            16480 non-null  object
 2   Source_type                                           16480 non-null  object
 3   Source_number                                         16480 non-null  object
 4   First_author                                          16480 non-null  object
 5   Year_published                                        16480 non-null  int64
 6   Elevation                                             2940 non-null   float64
 7   Prefecture                                            16480 non-null  object
 8   Municipality                                          16393 non-null  object
 9   Site_name                                             12305 non-null  object
 10  Latitude_(deg)                                        10209 non-null  float64
 11  Latitude_(min)                                        10209 non-null  float64
 12  Latitude_(sec)                                        9524 non-null   float64
 13  Longitude_(deg)                                       10209 non-null  float64
 14  Longitude_(min)                                       10209 non-null  float64
 15  Longitude_(sec)                                       9524 non-null   float64
 16  Flag_for_LatLon_coordinate                            10809 non-null  object
 17  Stand_age                                             3366 non-null   float64
 18  Tree_scientific_name_stand                            12708 non-null  object
 19  Tree_name_stand                                       12567 non-null  object
 20  Other_tree_composition_stand                          1743 non-null   object
 21  Forest_type                                           2750 non-null   object
 22  Leaf_habit                                            7455 non-null   object
 23  Leaf_shape                                            7480 non-null   object
 24  Tree_density                                          1492 non-null   object
 25  Tree_height                                           2236 non-null   object
 26  Diameter_at_breast_height                             2396 non-null   object
 27  Total_biomass                                         205 non-null    object
 28  LAI                                                   40 non-null     float64
 29  FAO_soil_type                                         1109 non-null   object
 30  Position_on_slope                                     1793 non-null   object
 31  Slope_aspect                                          489 non-null    object
 32  Sampling_year                                         16480 non-null  int64
 33  Sampling_month                                        15605 non-null  float64
 34  Sampling_day                                          13235 non-null  float64
 35  Corrected_year                                        14696 non-null  float64
 36  Corrected_month                                       14696 non-null  float64
 37  Corrected_day                                         14180 non-null  float64
 38  Detector                                              13686 non-null  object
 39  Flag_for_values                                       16415 non-null  object
 40  Item                                                  16480 non-null  object
 41  Parts                                                 13225 non-null  object
 42  Tree_scientific_name_sample                           10854 non-null  object
 43  Tree_name_sample                                      10609 non-null  object
 44  Sprout                                                175 non-null    object
 45  Leaf/ring_age                                         1396 non-null   object
 46  Upper_sampling_height                                 164 non-null    object
 47  Lower_sampling_height                                 164 non-null    float64
 48  Middle_sampling_height                                4085 non-null   object
 49  Upper_sampling_soil_depth                             2883 non-null   float64
 50  Lower_sampling_soil_depth                             2883 non-null   float64
 51  Middle_sampling_soil_depth                            2885 non-null   object
 52  Thickness_type_litter                                 451 non-null    object
 53  Mushroom_animal_scientific_name                       3392 non-null   object
 54  Mushroom_animal_name                                  3262 non-null   object
 55  Parts_animal                                          44 non-null     object
 56  Ecological_type_mushroom                              3189 non-null   object
 57  Wild_Grown_mushroom                                   2720 non-null   object
 58  Fresh_weight_basis                                    3218 non-null   float64
 59  Activity_concentration                                16136 non-null  object
 60  N_sample_act                                          9011 non-null   object
 61  Variance_act                                          2158 non-null   float64
 62  Variance_type_act                                     2008 non-null   object
 63  Minimum_act                                           50 non-null     float64
 64  Maximum_act                                           50 non-null     float64
 65  Inventory                                             3992 non-null   object
 66  N_inv                                                 2200 non-null   object
 67  Variance_inv                                          1339 non-null   object
 68  Variance_type_inv                                     1284 non-null   object
 69  Minimum_inv                                           78 non-null     float64
 70  Maximum_inv                                           78 non-null     float64
 71  Tag                                                   156 non-null    object
 72  Inventory_Soil_Tag                                    154 non-null    float64
 73  Japan_mesh_code                                       12230 non-null  float64
 74  Distance_from_FDNPP                                   11879 non-null  float64
 75  MEXT_dose                                             11879 non-null  float64
 76  Version_of_MEXT_dose                                  11879 non-null  datetime64[ns]
 77  MEXT_Cs134                                            11879 non-null  float64
 78  MEXT_Cs137                                            11879 non-null  float64
 79  Version_of_MEXT_Cs                                    11879 non-null  datetime64[ns]
 80  Mean_annual_temperature                               12230 non-null  float64
 81  Mean_annual_precipitation                             12230 non-null  float64
 82  Elevation_NLNI                                        12230 non-null  float64
 83  Japan_soil_type                                       12230 non-null  object
 84  modMEXT_Cs137_by_Kato_et_al._2019                     10703 non-null  float64
 85  Version_of_modMEXT                                    10703 non-null  datetime64[ns]
 86  Soil_profile_number                                   4133 non-null   float64
 87  Flag_duplication                                      730 non-null    float64
 88  Related_references                                    4227 non-null   object
 89  MEXT_Cs137_2011.3.11.corrected                        11879 non-null  float64
 90  modMEXT_Cs137_by_Kato_et_al._2019_2011.3.11corrected  10703 non-null  float64
 91  Sampling_date_estimated                               13228 non-null  datetime64[ns]
 92  Corrected_date_estimated                              11507 non-null  datetime64[ns]
 93  Activity_corrected_to_sampling_date                   13803 non-null  object
 94  Inventory_corrected_to_sampling_date                  5343 non-null   object
dtypes: datetime64[ns](5), float64(37), int64(3), object(50)
memory usage: 11.9+ MB

# View JSON-LD for BCO-DMO

In [27]:
import json
from pyld import jsonld
import os, sys

currentdir = os.path.dirname(os.path.abspath(''))
parentdir = os.path.dirname(currentdir)
sys.path.insert(0, parentdir)
from lib import jbutils
with open("./bcodmo.json") as dgraph:
    doc = json.load(dgraph)


frame = {
  "@context": {"@vocab": "https://schema.org/"},
  "@explicit": "true",
  "@requireAll": "true",
  "@type":     "Dataset",
  "variableMeasured": ""
}

context = {
    "@vocab": "https://schema.org/",
}

compacted = jsonld.compact(doc, context)

framed = jsonld.frame(compacted, frame)
jd = json.dumps(framed, indent=4)
# print(jd)

# jbutils.show_graph(framed) ## turned off for now..  kinda pointless